spring:
  datasource:
    url: jdbc:mysql://localhost:3306/karrot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dlehdgus12
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true