server:
  port: 8080

spring:
  application:
    name: springstudy

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.dku.springstudy: DEBUG

jwt:
  secret-key: kangho



