package com.dku.springstudy.enums;

public enum Category {
    DIGITAL, ELECTRONIC, FURNITURE_INTERIOR, KIDS, LIFE_FOOD, BOOK_KIDS, SPORTS, WOMAN_MERCHANDISE, WOMAN_CLOTHES, MAN_MERCHANDISE_CLOTHES,
    GAME_HOBBY, BEAUTY_HAIR, PET, BOOK_TICKET_MUSIC, PLANTS, USED_THINGS, USED_CAR
}
